## PROJECT: Sentiment Analysis for Alexa Reviews in Amazon
- Reading the data - Alexa Reviews are downloaded from Kaggle
- Text Preprocessing
- One hot encoding
- BoW
- TF- IDF
- ML

## Reading the data

In [47]:
# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("sid321axn/amazon-alexa-reviews")

# print("Path to dataset files:", path)

#Reading the data
import pandas as pd
data = pd.read_csv(r"D:\GEN_AI_BOOTCAMP\Live_Classes1\Assignments\Data\amazon_alexa.tsv", sep='\t')
data.head()
#distinct values in the feedback column
#cross tab between rating and feedback

# data.to_excel(r"D:\GEN_AI_BOOTCAMP\Live_Classes1\Assignments\Data\alexa_reviews.xlsx", index=False)    #Output for Sunny
pd.crosstab(data['rating'], data['feedback'])

feedback    0     1
rating
1         161     0
2          96     0
3           0   152
4           0   455
5           0  2286

#### The dataset shows sentiment 1 for rating above 2 and 1,2 as negative sentiment

In [48]:
#print the column names
print(data.columns)

Index(['rating', 'date', 'variation', 'verified_reviews', 'feedback'], dtype='str')

In [49]:
#Converting the reviews in list of sentence
data = data[data["verified_reviews"].apply(lambda x: isinstance(x, str))] # removing records with non-string reviews
data = data[data["verified_reviews"] != " "] # removing records with blank reviews
reviews = data["verified_reviews"].tolist()
print(pd.crosstab(data['rating'], data['feedback']))
print(reviews[:5])

feedback    0     1
rating
1         146     0
2          91     0
3           0   140
4           0   447
5           0  2246
['Love my Echo!', 'Loved it!', 'Sometimes while playing a game, you can answer a question correctly but Alexa says you got it wrong and answers the same as you.  I like being able to turn lights on and off while away from home.', 'I have had a lot of fun with this thing. My 4 yr old learns about dinosaurs, i control the lights and play games like categories. Has nice sound when playing music as well.', 'Music']

###### 3 non strings records removed

## Text Preprocessing

In [50]:
#Text preprocessing including lowercasing, removing punctuation and stop words,stopwords,lametisation
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# nltk.download("stopwords")
# nltk.download("wordnet")
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return " ".join(lemmatized_tokens)
preprocessed_reviews = [preprocess_text(review) for review in reviews]

#Removing Punctuation
import string
def remove_punctuation(text):
    return text.translate(str.maketrans("", "", string.punctuation))
reviews_cleaned = [remove_punctuation(review) for review in preprocessed_reviews]


#remove hyphens
def remove_hyphens(text):
    return text.replace("-", " ")
reviews_cleaned = [remove_hyphens(review) for review in reviews_cleaned]
reviews_cleaned[:5]

['love echo',
 'loved',
 'sometimes playing game answer question correctly alexa say got wrong answer like able turn light away home',
 'lot fun thing 4 yr old learns dinosaur control light play game like category nice sound playing music well',
 'music']

In [51]:
#Need to merge the cleaned reviews with the main dataframe
data["cleaned_review"] = reviews_cleaned
data=data[data["cleaned_review"] != " "]
data=data[data["cleaned_review"] != ""]  # removing records with blank cleaned reviews
len(data)

3063

## Tokenisation

In [59]:
#Tokenisation of reviews_cleaned
reviews_cleaned = data["cleaned_review"].tolist()
tokenized_reviews = [review.split() for review in reviews_cleaned]
tokenized_reviews [:5]

[['love', 'echo'],
 ['loved'],
 ['sometimes',
  'playing',
  'game',
  'answer',
  'question',
  'correctly',
  'alexa',
  'say',
  'got',
  'wrong',
  'answer',
  'like',
  'able',
  'turn',
  'light',
  'away',
  'home'],
 ['lot',
  'fun',
  'thing',
  '4',
  'yr',
  'old',
  'learns',
  'dinosaur',
  'control',
  'light',
  'play',
  'game',
  'like',
  'category',
  'nice',
  'sound',
  'playing',
  'music',
  'well'],
 ['music']]

In [60]:
#Specific format
all_words = [[word] for review in tokenized_reviews for word in review]
all_words[:5]

[['love'], ['echo'], ['loved'], ['sometimes'], ['playing']]

## One hot encoding

In [61]:
#fit one hot encoding
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
encoder.fit(all_words)
print("Vocabulary:", encoder.categories_[0])
encoder.categories_[0].shape

Vocabulary: ['072318' '1' '10' ... 'zzzzzzz' 'í' 'útil']

(4021,)

In [56]:
a = 0
for idx, sentence in enumerate(tokenized_reviews):
    arr = np.array(sentence)
   
    if arr.ndim == 1:
        a=a+1   
    
print(a)

3070

In [62]:
#One hot encoding for reviews cleaned
import numpy as np
for sentence in tokenized_reviews:
    # sentence=np.array(sentence).reshape(-1, 1)
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print(encoded_sentence)
    print("Dimension:", encoded_sentence.shape)

Sentence: ['love', 'echo']
  (0, 2154)	1.0
  (1, 1190)	1.0
Dimension: (2, 4021)

Sentence: ['loved']
  (0, 2155)	1.0
Dimension: (1, 4021)

Sentence: ['sometimes', 'playing', 'game', 'answer', 'question', 'correctly', 'alexa', 'say', 'got', 'wrong', 'answer', 'like', 'able', 'turn', 'light', 'away', 'home']
  (0, 3275)	1.0
  (1, 2633)	1.0
  (2, 1526)	1.0
  (3, 325)	1.0
  (4, 2793)	1.0
  (5, 893)	1.0
  (6, 262)	1.0
  (7, 3048)	1.0
  (8, 1587)	1.0
  (9, 3980)	1.0
  (10, 325)	1.0
  (11, 2087)	1.0
  (12, 151)	1.0
  (13, 3693)	1.0
  (14, 2077)	1.0
  (15, 433)	1.0
  (16, 1733)	1.0
Dimension: (17, 4021)

Sentence: ['lot', 'fun', 'thing', '4', 'yr', 'old', 'learns', 'dinosaur', 'control', 'light', 'play', 'game', 'like', 'category', 'nice', 'sound', 'playing', 'music', 'well']
  (0, 2148)	1.0
  (1, 1505)	1.0
  (2, 3571)	1.0
  (3, 109)	1.0
  (4, 4010)	1.0
  (5, 2445)	1.0
  (6, 2056)	1.0
  (7, 1076)	1.0
  (8, 868)	1.0
  (9, 2077)	1.0
  (10, 2630)	1.0
  (11, 1526)	1.0
  (12, 2087)	1.0
  (13, 665)	1.0
  (14, 2376)	1.0
  (15, 3296)	1.0
  (16, 2633)	1.0
  (17, 2310)	1.0
  (18, 3906)	1.0
Dimension: (19, 4021)

Sentence: ['music']
  (0, 2310)	1.0
Dimension: (1, 4021)

Sentence: ['received', 'echo', 'gift', 'needed', 'another', 'bluetooth', 'something', 'play', 'music', 'easily', 'accessible', 'found', 'smart', 'speaker', 'cant', 'wait', 'see', 'else']
  (0, 2857)	1.0
  (1, 1190)	1.0
  (2, 1558)	1.0
  (3, 2349)	1.0
  (4, 324)	1.0
  (5, 541)	1.0
  (6, 3273)	1.0
  (7, 2630)	1.0
  (8, 2310)	1.0
  (9, 1186)	1.0
  (10, 162)	1.0
  (11, 1484)	1.0
  (12, 3237)	1.0
  (13, 3319)	1.0
  (14, 644)	1.0
  (15, 3856)	1.0
  (16, 3092)	1.0
  (17, 1230)	1.0
Dimension: (18, 4021)

Sentence: ['without', 'cellphone', 'cannot', 'use', 'many', 'feature', 'ipad', 'see', 'use', 'great', 'alarm', 'u', 'r', 'almost', 'deaf', 'hear', 'alarm', 'bedroom', 'living', 'room', 'reason', 'enough', 'keep', 'herit', 'fun', 'ask', 'random', 'question', 'hear', 'response', 'seem', 'smartbon', 'politics', 'yet']
  (0, 3947)	1.0
  (1, 677)	1.0
  (2, 643)	1.0
  (3, 3783)	1.0
  (4, 2201)	1.0
  (5, 1408)	1.0
  (6, 1923)	1.0
  (7, 3092)	1.0
  (8, 3783)	1.0
  (9, 1606)	1.0
  (10, 254)	1.0
  (11, 3715)	1.0
  (12, 2808)	1.0
  (13, 283)	1.0
  (14, 975)	1.0
  (15, 1686)	1.0
  (16, 254)	1.0
  (17, 486)	1.0
  (18, 2112)	1.0
  (19, 3006)	1.0
  (20, 2847)	1.0
  (21, 1260)	1.0
  (22, 1987)	1.0
  (23, 1706)	1.0
  (24, 1505)	1.0
  (25, 384)	1.0
  (26, 2818)	1.0
  (27, 2793)	1.0
  (28, 1686)	1.0
  (29, 2972)	1.0
  (30, 3094)	1.0
  (31, 3238)	1.0
  (32, 2661)	1.0
  (33, 3996)	1.0
Dimension: (34, 4021)

Sentence: ['think', '5th', 'one', 'ive', 'purchased', 'im', 'working', 'getting', 'one', 'every', 'room', 'house', 'really', 'like', 'feature', 'offer', 'specifily', 'playing', 'music', 'echo', 'controlling', 'light', 'throughout', 'house']
  (0, 3575)	1.0
  (1, 121)	1.0
  (2, 2452)	1.0
  (3, 1958)	1.0
  (4, 2776)	1.0
  (5, 1790)	1.0
  (6, 3961)	1.0
  (7, 1555)	1.0
  (8, 2452)	1.0
  (9, 1303)	1.0
  (10, 3006)	1.0
  (11, 1754)	1.0
  (12, 2846)	1.0
  (13, 2087)	1.0
  (14, 1408)	1.0
  (15, 2434)	1.0
  (16, 3331)	1.0
  (17, 2633)	1.0
  (18, 2310)	1.0
  (19, 1190)	1.0
  (20, 872)	1.0
  (21, 2077)	1.0
  (22, 3589)	1.0
  (23, 1754)	1.0
Dimension: (24, 4021)

Sentence: ['look', 'great']
  (0, 2136)	1.0
  (1, 1606)	1.0
Dimension: (2, 4021)

Sentence: ['love', 'ive', 'listened', 'song', 'havent', 'heard', 'since', 'childhood', 'get', 'news', 'weather', 'information', 'great']
  (0, 2154)	1.0
  (1, 1958)	1.0
  (2, 2102)	1.0
  (3, 3278)	1.0
  (4, 1672)	1.0
  (5, 1687)	1.0
  (6, 3196)	1.0
  (7, 715)	1.0
  (8, 1554)	1.0
  (9, 2369)	1.0
  (10, 3893)	1.0
  (11, 1845)	1.0
  (12, 1606)	1.0
Dimension: (13, 4021)

Sentence: ['sent', '85', 'year', 'old', 'dad', 'talk', 'constantly']
  (0, 3114)	1.0
  (1, 136)	1.0
  (2, 3988)	1.0
  (3, 2445)	1.0
  (4, 955)	1.0
  (5, 3501)	1.0
  (6, 853)	1.0
Dimension: (7, 4021)

Sentence: ['love', 'learning', 'knew', 'thing', 'eveyday', 'still', 'figuring', 'everything', 'work', 'far', 'easy', 'use', 'understand', 'make', 'laugh', 'time']
  (0, 2154)	1.0
  (1, 2055)	1.0
  (2, 2006)	1.0
  (3, 3571)	1.0
  (4, 1312)	1.0
  (5, 3399)	1.0
  (6, 1428)	1.0
  (7, 1308)	1.0
  (8, 3957)	1.0
  (9, 1395)	1.0
  (10, 1188)	1.0
  (11, 3783)	1.0
  (12, 3727)	1.0
  (13, 2186)	1.0
  (14, 2043)	1.0
  (15, 3603)	1.0
Dimension: (16, 4021)

Sentence: ['purchased', 'mother', 'knee', 'problem', 'give', 'something', 'trying', 'come', 'getting', 'around', 'fast', 'like', 'didshe', 'enjoys', 'little', 'big', 'thing', 'doalexa', 'play', 'song', 'time', 'cook']
  (0, 2776)	1.0
  (1, 2295)	1.0
  (2, 2005)	1.0
  (3, 2723)	1.0
  (4, 1561)	1.0
  (5, 3273)	1.0
  (6, 3688)	1.0
  (7, 773)	1.0
  (8, 1555)	1.0
  (9, 372)	1.0
  (10, 1400)	1.0
  (11, 2087)	1.0
  (12, 1055)	1.0
  (13, 1259)	1.0
  (14, 2108)	1.0
  (15, 516)	1.0
  (16, 3571)	1.0
  (17, 1123)	1.0
  (18, 2630)	1.0
  (19, 3278)	1.0
  (20, 3603)	1.0
  (21, 878)	1.0
Dimension: (22, 4021)

Sentence: ['love', 'love', 'love']
  (0, 2154)	1.0
  (1, 2154)	1.0
  (2, 2154)	1.0
Dimension: (3, 4021)

Sentence: ['expected']
  (0, 1344)	1.0
Dimension: (1, 4021)

Sentence: ['love', 'wife', 'hate']
  (0, 2154)	1.0
  (1, 3934)	1.0
  (2, 1668)	1.0
Dimension: (3, 4021)

Sentence: ['really', 'happy', 'purchase', 'great', 'speaker', 'easy', 'set']
  (0, 2846)	1.0
  (1, 1658)	1.0
  (2, 2775)	1.0
  (3, 1606)	1.0
  (4, 3319)	1.0
  (5, 1188)	1.0
  (6, 3127)	1.0
Dimension: (7, 4021)

Sentence: ['using', 'alexa', 'couple', 'day', 'lot', 'fun', 'new', 'toy', 'like', 'new', 'household', 'member', 'trying', 'learn', 'different', 'featues', 'benefit', 'come']
  (0, 3793)	1.0
  (1, 262)	1.0
  (2, 905)	1.0
  (3, 968)	1.0
  (4, 2148)	1.0
  (5, 1505)	1.0
  (6, 2365)	1.0
  (7, 3650)	1.0
  (8, 2087)	1.0
  (9, 2365)	1.0
  (10, 1756)	1.0
  (11, 2231)	1.0
  (12, 3688)	1.0
  (13, 2052)	1.0
  (14, 1059)	1.0
  (15, 1407)	1.0
  (16, 500)	1.0
  (17, 773)	1.0
Dimension: (18, 4021)

Sentence: ['love', 'size', '2nd', 'generation', 'echo', 'still', 'need', 'little', 'improvement', 'sound']
  (0, 2154)	1.0
  (1, 3213)	1.0
  (2, 36)	1.0
  (3, 1548)	1.0
  (4, 1190)	1.0
  (5, 3399)	1.0
  (6, 2348)	1.0
  (7, 2108)	1.0
  (8, 1807)	1.0
  (9, 3296)	1.0
Dimension: (10, 4021)

Sentence: ['liked', 'original', 'echo', 'shorter', 'greater', 'fabriccolor', 'choice', 'miss', 'volume', 'ring', 'top', 'plusminus', 'button', 'big', 'deal', 'ring', 'w', 'comforting', 'well', 'like', 'use', 'standard', 'usb', 'charger', 'port', 'instead', 'previous', 'round', 'pin', 'guess', 'sound', 'seems', 'work', 'still', 'answer', 'alexaechocomputer', 'whats', 'like']
  (0, 2088)	1.0
  (1, 2489)	1.0
  (2, 1190)	1.0
  (3, 3159)	1.0
  (4, 1607)	1.0
  (5, 1371)	1.0
  (6, 717)	1.0
  (7, 2272)	1.0
  (8, 3852)	1.0
  (9, 2999)	1.0
  (10, 3636)	1.0
  (11, 2650)	1.0
  (12, 615)	1.0
  (13, 516)	1.0
  (14, 976)	1.0
  (15, 2999)	1.0
  (16, 3855)	1.0
  (17, 777)	1.0
  (18, 3906)	1.0
  (19, 2087)	1.0
  (20, 3783)	1.0
  (21, 3372)	1.0
  (22, 3781)	1.0
  (23, 700)	1.0
  (24, 2668)	1.0
  (25, 1870)	1.0
  (26, 2707)	1.0
  (27, 3017)	1.0
  (28, 2617)	1.0
  (29, 1631)	1.0
  (30, 3296)	1.0
  (31, 3096)	1.0
  (32, 3957)	1.0
  (33, 3399)	1.0
  (34, 325)	1.0
  (35, 265)	1.0
  (36, 3917)	1.0
  (37, 2087)	1.0
Dimension: (38, 4021)

Sentence: ['love', 'echo', 'good', 'music', 'sound', 'playing', 'alexa', 'understands', 'command', 'difficult', 'time', 'find', 'specific', 'playlist', 'song', 'spotify', 'good', 'amazon', 'music', 'lacking', 'major', 'program']
  (0, 2154)	1.0
  (1, 1190)	1.0
  (2, 1579)	1.0
  (3, 2310)	1.0
  (4, 3296)	1.0
  (5, 2633)	1.0
  (6, 262)	1.0
  (7, 3730)	1.0
  (8, 779)	1.0
  (9, 1062)	1.0
  (10, 3603)	1.0
  (11, 1433)	1.0
  (12, 3329)	1.0
  (13, 2635)	1.0
  (14, 3278)	1.0
  (15, 3353)	1.0
  (16, 1579)	1.0
  (17, 305)	1.0
  (18, 2310)	1.0
  (19, 2024)	1.0
  (20, 2184)	1.0
  (21, 2738)	1.0
Dimension: (22, 4021)

Sentence: ['love', 'alexa', 'use', 'play', 'music', 'play', 'radio', 'itunes', 'play', 'podcasts', 'anypod', 'set', 'reminder', 'listen', 'flash', 'briefing', 'news', 'weather', 'every', 'morning', 'rely', 'custom', 'list', 'like', 'able', 'voice', 'control', 'volume', 'sure', 'well', 'continue', 'find', 'new', 'usessometimes', 'bit', 'frustrating', 'alexa', 'doesnt', 'understand', 'saying']
  (0, 2154)	1.0
  (1, 262)	1.0
  (2, 3783)	1.0
  (3, 2630)	1.0
  (4, 2310)	1.0
  (5, 2630)	1.0
  (6, 2809)	1.0
  (7, 1955)	1.0
  (8, 2630)	1.0
  (9, 2655)	1.0
  (10, 337)	1.0
  (11, 3127)	1.0
  (12, 2922)	1.0
  (13, 2101)	1.0
  (14, 1454)	1.0
  (15, 578)	1.0
  (16, 2369)	1.0
  (17, 3893)	1.0
  (18, 1303)	1.0
  (19, 2293)	1.0
  (20, 2913)	1.0
  (21, 942)	1.0
  (22, 2100)	1.0
  (23, 2087)	1.0
  (24, 151)	1.0
  (25, 3845)	1.0
  (26, 868)	1.0
  (27, 3852)	1.0
  (28, 3470)	1.0
  (29, 3906)	1.0
  (30, 863)	1.0
  (31, 1433)	1.0
  (32, 2365)	1.0
  (33, 3792)	1.0
  (34, 525)	1.0
  (35, 1496)	1.0
  (36, 262)	1.0
  (37, 1128)	1.0
  (38, 3727)	1.0
  (39, 3049)	1.0
Dimension: (40, 4021)

Sentence: ['set', 'day', 'still', 'adding', 'smart', 'home', 'device', 'speaker', 'great', 'playing', 'music', 'like', 'size', 'stationed', 'kitchen', 'counter', 'intrusive', 'look']
  (0, 3127)	1.0
  (1, 968)	1.0
  (2, 3399)	1.0
  (3, 201)	1.0
  (4, 3237)	1.0
  (5, 1733)	1.0
  (6, 1042)	1.0
  (7, 3319)	1.0
  (8, 1606)	1.0
  (9, 2633)	1.0
  (10, 2310)	1.0
  (11, 2087)	1.0
  (12, 3213)	1.0
  (13, 3386)	1.0
  (14, 2002)	1.0
  (15, 901)	1.0
  (16, 1909)	1.0
  (17, 2136)	1.0
Dimension: (18, 4021)

Sentence: ['love', 'play', 'sleep', 'sound', 'immediately', 'ask']
  (0, 2154)	1.0
  (1, 2630)	1.0
  (2, 3222)	1.0
  (3, 3296)	1.0
  (4, 1796)	1.0
  (5, 384)	1.0
Dimension: (6, 4021)

Sentence: ['got', 'second', 'unit', 'bedroom', 'expecting', 'sound', 'improved', 'didnt', 'really', 'see', 'difference', 'overall', 'big', 'improvement', '1st', 'generation']
  (0, 1587)	1.0
  (1, 3087)	1.0
  (2, 3740)	1.0
  (3, 486)	1.0
  (4, 1346)	1.0
  (5, 3296)	1.0
  (6, 1806)	1.0
  (7, 1054)	1.0
  (8, 2846)	1.0
  (9, 3092)	1.0
  (10, 1058)	1.0
  (11, 2505)	1.0
  (12, 516)	1.0
  (13, 1807)	1.0
  (14, 20)	1.0
  (15, 1548)	1.0
Dimension: (16, 4021)

Sentence: ['amazing', 'product']
  (0, 303)	1.0
  (1, 2728)	1.0
Dimension: (2, 4021)

Sentence: ['love', 'echo', 'easy', 'operate', 'load', 'funit', 'everything', 'advertised', 'use', 'mainly', 'play', 'favorite', 'tune', 'test', 'alexas', 'knowledge']
  (0, 2154)	1.0
  (1, 1190)	1.0
  (2, 1188)	1.0
  (3, 2469)	1.0
  (4, 2118)	1.0
  (5, 1512)	1.0
  (6, 1308)	1.0
  (7, 223)	1.0
  (8, 3783)	1.0
  (9, 2178)	1.0
  (10, 2630)	1.0
  (11, 1406)	1.0
  (12, 3691)	1.0
  (13, 3547)	1.0
  (14, 266)	1.0
  (15, 2013)	1.0
Dimension: (16, 4021)

Sentence: ['sound', 'great', 'love']
  (0, 3296)	1.0
  (1, 1606)	1.0
  (2, 2154)	1.0
Dimension: (3, 4021)

Sentence: ['fun', 'item', 'play', 'get', 'used', 'using', 'sometimes', 'hard', 'time', 'answering', 'question', 'ask', 'think', 'better']
  (0, 1505)	1.0
  (1, 1945)	1.0
  (2, 2630)	1.0
  (3, 1554)	1.0
  (4, 3785)	1.0
  (5, 3793)	1.0
  (6, 3275)	1.0
  (7, 1659)	1.0
  (8, 3603)	1.0
  (9, 327)	1.0
  (10, 2793)	1.0
  (11, 384)	1.0
  (12, 3575)	1.0
  (13, 507)	1.0
Dimension: (14, 4021)

Sentence: ['like', 'one']
  (0, 2087)	1.0
  (1, 2452)	1.0
Dimension: (2, 4021)

Sentence: ['still', 'learning', 'capabilitiesbut', 'far', 'pretty', 'pretty', 'pretty', 'good']
  (0, 3399)	1.0
  (1, 2055)	1.0
  (2, 645)	1.0
  (3, 1395)	1.0
  (4, 2703)	1.0
  (5, 2703)	1.0
  (6, 2703)	1.0
  (7, 1579)	1.0
Dimension: (8, 4021)

Sentence: ['like']
  (0, 2087)	1.0
Dimension: (1, 4021)

Sentence: ['work', 'well', 'need', 'learning', 'command', 'unique', 'owner', 'user', 'like', 'alexa', 'learn', 'tashas', 'birthday', 'alexa', 'learn', 'definition', 'fine', 'etc', 'great']
  (0, 3957)	1.0
  (1, 3906)	1.0
  (2, 2348)	1.0
  (3, 2055)	1.0
  (4, 779)	1.0
  (5, 3739)	1.0
  (6, 2518)	1.0
  (7, 3791)	1.0
  (8, 2087)	1.0
  (9, 262)	1.0
  (10, 2052)	1.0
  (11, 3511)	1.0
  (12, 523)	1.0
  (13, 262)	1.0
  (14, 2052)	1.0
  (15, 1002)	1.0
  (16, 1435)	1.0
  (17, 1289)	1.0
  (18, 1606)	1.0
Dimension: (19, 4021)

Sentence: ['speaker', 'sound', 'pretty', 'good', 'small', 'setup', 'pretty', 'easy', 'bought', 'two', 'reason', 'rate', '3', 'followed', 'instruction', 'synching', 'music', 'unit', 'know', 'ive', 'done', 'correctly', 'wont', 'sync', 'primary', 'motivation', 'purchasing', 'multiple', 'unit']
  (0, 3319)	1.0
  (1, 3296)	1.0
  (2, 2703)	1.0
  (3, 1579)	1.0
  (4, 3235)	1.0
  (5, 3132)	1.0
  (6, 2703)	1.0
  (7, 1188)	1.0
  (8, 566)	1.0
  (9, 3705)	1.0
  (10, 2847)	1.0
  (11, 2826)	1.0
  (12, 40)	1.0
  (13, 1467)	1.0
  (14, 1871)	1.0
  (15, 3490)	1.0
  (16, 2310)	1.0
  (17, 3740)	1.0
  (18, 2010)	1.0
  (19, 1958)	1.0
  (20, 1134)	1.0
  (21, 893)	1.0
  (22, 3953)	1.0
  (23, 3487)	1.0
  (24, 2714)	1.0
  (25, 2297)	1.0
  (26, 2779)	1.0
  (27, 2309)	1.0
  (28, 3740)	1.0
Dimension: (29, 4021)

Sentence: ['device', 'awesome']
  (0, 1042)	1.0
  (1, 434)	1.0
Dimension: (2, 4021)

Sentence: ['bought', 'compare', 'speaker', 'quality', 'first', 'generation', 'speaker', 'like', 'sound', 'better', 'ship', 'daughter', 'though', 'like', 'fact', 'first', 'generation', 'chargeable', 'base', 'bought', 'keep', 'mobile', 'need', 'better', 'sound']
  (0, 566)	1.0
  (1, 800)	1.0
  (2, 3319)	1.0
  (3, 2788)	1.0
  (4, 1445)	1.0
  (5, 1548)	1.0
  (6, 3319)	1.0
  (7, 2087)	1.0
  (8, 3296)	1.0
  (9, 507)	1.0
  (10, 3146)	1.0
  (11, 967)	1.0
  (12, 3584)	1.0
  (13, 2087)	1.0
  (14, 1376)	1.0
  (15, 1445)	1.0
  (16, 1548)	1.0
  (17, 699)	1.0
  (18, 463)	1.0
  (19, 566)	1.0
  (20, 1987)	1.0
  (21, 2279)	1.0
  (22, 2348)	1.0
  (23, 507)	1.0
  (24, 3296)	1.0
Dimension: (25, 4021)

Sentence: ['love', 'echo', 'still', 'learning', 'thing', 'wasnt', 'able', 'follow', 'instruction', 'included', 'package', 'found', 'great', 'one', 'utube']
  (0, 2154)	1.0
  (1, 1190)	1.0
  (2, 3399)	1.0
  (3, 2055)	1.0
  (4, 3571)	1.0
  (5, 3877)	1.0
  (6, 151)	1.0
  (7, 1466)	1.0
  (8, 1871)	1.0
  (9, 1816)	1.0
  (10, 2521)	1.0
  (11, 1484)	1.0
  (12, 1606)	1.0
  (13, 2452)	1.0
  (14, 3800)	1.0
Dimension: (15, 4021)

Sentence: ['speaker', 'better', '1st', 'generation', 'echo']
  (0, 3319)	1.0
  (1, 507)	1.0
  (2, 20)	1.0
  (3, 1548)	1.0
  (4, 1190)	1.0
Dimension: (5, 4021)

Sentence: ['thing', 'way', 'cool', 'get', 'one', 'want', 'cool']
  (0, 3571)	1.0
  (1, 3888)	1.0
  (2, 880)	1.0
  (3, 1554)	1.0
  (4, 2452)	1.0
  (5, 3867)	1.0
  (6, 880)	1.0
Dimension: (7, 4021)

Sentence: ['first', 'digital', 'assistant', 'im', 'giving', 'good', 'review', 'speaker', 'really', 'good', 'cheap', 'price', 'prime', 'day', 'fun', 'play', 'used', 'alarm', 'clock', 'thats', 'going', 'get', 'first', 'place', 'ended', 'echo', 'havent', 'go', 'one', 'definitely', 'try', 'itwhat', 'like', 'best', 'number', 'device', 'connect', 'purchase', 'came', 'smart', 'plug', '10', 'connect', 'lamp', 'alexa', 'turn', 'light']
  (0, 1445)	1.0
  (1, 1065)	1.0
  (2, 395)	1.0
  (3, 1790)	1.0
  (4, 1563)	1.0
  (5, 1579)	1.0
  (6, 2990)	1.0
  (7, 3319)	1.0
  (8, 2846)	1.0
  (9, 1579)	1.0
  (10, 708)	1.0
  (11, 2709)	1.0
  (12, 2715)	1.0
  (13, 968)	1.0
  (14, 1505)	1.0
  (15, 2630)	1.0
  (16, 3785)	1.0
  (17, 254)	1.0
  (18, 747)	1.0
  (19, 3558)	1.0
  (20, 1575)	1.0
  (21, 1554)	1.0
  (22, 1445)	1.0
  (23, 2621)	1.0
  (24, 1245)	1.0
  (25, 1190)	1.0
  (26, 1672)	1.0
  (27, 1572)	1.0
  (28, 2452)	1.0
  (29, 1001)	1.0
  (30, 3686)	1.0
  (31, 1956)	1.0
  (32, 2087)	1.0
  (33, 503)	1.0
  (34, 2419)	1.0
  (35, 1042)	1.0
  (36, 837)	1.0
  (37, 2775)	1.0
  (38, 634)	1.0
  (39, 3237)	1.0
  (40, 2644)	1.0
  (41, 2)	1.0
  (42, 837)	1.0
  (43, 2029)	1.0
  (44, 262)	1.0
  (45, 3693)	1.0
  (46, 2077)	1.0
Dimension: (47, 4021)

Sentence: ['husband', 'like', 'able', 'use', 'listen', 'music', 'wish', 'knew', 'capability']
  (0, 1772)	1.0
  (1, 2087)	1.0
  (2, 151)	1.0
  (3, 3783)	1.0
  (4, 2101)	1.0
  (5, 2310)	1.0
  (6, 3942)	1.0
  (7, 2006)	1.0
  (8, 646)	1.0
Dimension: (9, 4021)

Sentence: ['android', 'would', 'allow', 'alexa', 'connect', 'fortunately', 'sister', 'apple', 'cell', 'hour', 'tech', 'support', 'fixed', 'glitch', 'running']
  (0, 320)	1.0
  (1, 3974)	1.0
  (2, 278)	1.0
  (3, 262)	1.0
  (4, 837)	1.0
  (5, 1481)	1.0
  (6, 3206)	1.0
  (7, 353)	1.0
  (8, 676)	1.0
  (9, 1753)	1.0
  (10, 3518)	1.0
  (11, 3465)	1.0
  (12, 1450)	1.0
  (13, 1568)	1.0
  (14, 3026)	1.0
Dimension: (15, 4021)

Sentence: ['far', 'good']
  (0, 1395)	1.0
  (1, 1579)	1.0
Dimension: (2, 4021)

Sentence: ['tried', 'play', 'certain', 'broadway', 'show', 'like', 'camelot', 'give', 'ne', 'group', 'camelot']
  (0, 3673)	1.0
  (1, 2630)	1.0
  (2, 680)	1.0
  (3, 584)	1.0
  (4, 3164)	1.0
  (5, 2087)	1.0
  (6, 635)	1.0
  (7, 1561)	1.0
  (8, 2343)	1.0
  (9, 1624)	1.0
  (10, 635)	1.0
Dimension: (11, 4021)

Sentence: ['great']
  (0, 1606)	1.0
Dimension: (1, 4021)

Sentence: ['satisfied', 'echo', 'alexa', 'control', 'light', 'family', 'room', 'wife', 'listen', 'jimmy', 'buffet', 'asking', 'alexa']
  (0, 3040)	1.0
  (1, 1190)	1.0
  (2, 262)	1.0
  (3, 868)	1.0
  (4, 2077)	1.0
  (5, 1390)	1.0
  (6, 3006)	1.0
  (7, 3934)	1.0
  (8, 2101)	1.0
  (9, 1970)	1.0
  (10, 594)	1.0
  (11, 387)	1.0
  (12, 262)	1.0
Dimension: (13, 4021)

Sentence: ['like', 'siri', 'fact', 'siri', 'answer', 'accurately', 'alexa', 'dont', 'see', 'real', 'need', 'household', 'though', 'good', 'bargain', 'prime', 'day', 'deal']
  (0, 2087)	1.0
  (1, 3203)	1.0
  (2, 1376)	1.0
  (3, 3203)	1.0
  (4, 325)	1.0
  (5, 177)	1.0
  (6, 262)	1.0
  (7, 1136)	1.0
  (8, 3092)	1.0
  (9, 2841)	1.0
  (10, 2348)	1.0
  (11, 1756)	1.0
  (12, 3584)	1.0
  (13, 1579)	1.0
  (14, 458)	1.0
  (15, 2715)	1.0
  (16, 968)	1.0
  (17, 976)	1.0
Dimension: (18, 4021)

Sentence: ['love', 'echo', 'still', 'learning', 'every', 'thing', 'work', 'ton', 'fun']
  (0, 2154)	1.0
  (1, 1190)	1.0
  (2, 3399)	1.0
  (3, 2055)	1.0
  (4, 1303)	1.0
  (5, 3571)	1.0
  (6, 3957)	1.0
  (7, 3630)	1.0
  (8, 1505)	1.0
Dimension: (9, 4021)

Sentence: ['love', 'much']
  (0, 2154)	1.0
  (1, 2306)	1.0
Dimension: (2, 4021)

Sentence: ['different', 'apple', 'play', 'specific', 'list', 'music', 'must', 'amazon', 'spotify', 'plusprimeetc', 'account', 'must', 'pay', 'play', 'music', '3', 'star', 'reason', 'everything', 'else']
  (0, 1059)	1.0
  (1, 353)	1.0
  (2, 2630)	1.0
  (3, 3329)	1.0
  (4, 2100)	1.0
  (5, 2310)	1.0
  (6, 2320)	1.0
  (7, 305)	1.0
  (8, 3353)	1.0
  (9, 2651)	1.0
  (10, 174)	1.0
  (11, 2320)	1.0
  (12, 2561)	1.0
  (13, 2630)	1.0
  (14, 2310)	1.0
  (15, 40)	1.0
  (16, 3375)	1.0
  (17, 2847)	1.0
  (18, 1308)	1.0
  (19, 1230)	1.0
Dimension: (20, 4021)

Sentence: ['excelente', 'lo', 'unico', 'e', 'que', 'esta', 'en', 'español']
  (0, 1323)	1.0
  (1, 2117)	1.0
  (2, 3736)	1.0
  (3, 1178)	1.0
  (4, 2790)	1.0
  (5, 1284)	1.0
  (6, 1239)	1.0
  (7, 1280)	1.0
Dimension: (8, 4021)

Sentence: ['im', 'still', 'learning', 'use', 'far', 'echo', 'great', 'sound', 'actually', 'much', 'better', 'expecting']
  (0, 1790)	1.0
  (1, 3399)	1.0
  (2, 2055)	1.0
  (3, 3783)	1.0
  (4, 1395)	1.0
  (5, 1190)	1.0
  (6, 1606)	1.0
  (7, 3296)	1.0
  (8, 192)	1.0
  (9, 2306)	1.0
  (10, 507)	1.0
  (11, 1346)	1.0
Dimension: (12, 4021)

Sentence: ['work', 'youd', 'expect', 'also', 'good', 'sound', 'quality', 'considering', 'price', '7000', 'sale', 'feature']
  (0, 3957)	1.0
  (1, 4000)	1.0
  (2, 1342)	1.0
  (3, 293)	1.0
  (4, 1579)	1.0
  (5, 3296)	1.0
  (6, 2788)	1.0
  (7, 848)	1.0
  (8, 2709)	1.0
  (9, 129)	1.0
  (10, 3033)	1.0
  (11, 1408)	1.0
Dimension: (12, 4021)

Sentence: ['sound', 'echo', '2nd', 'generation', 'phenomenal', 'mention', 'love', 'alexa', 'helpful']
  (0, 3296)	1.0
  (1, 1190)	1.0
  (2, 36)	1.0
  (3, 1548)	1.0
  (4, 2597)	1.0
  (5, 2234)	1.0
  (6, 2154)	1.0
  (7, 262)	1.0
  (8, 1702)	1.0
Dimension: (9, 4021)

Sentence: ['like', 'google', 'better']
  (0, 2087)	1.0
  (1, 1585)	1.0
  (2, 507)	1.0
Dimension: (3, 4021)

Sentence: ['let', 'play', 'learn', 'get']
  (0, 2069)	1.0
  (1, 2630)	1.0
  (2, 2052)	1.0
  (3, 1554)	1.0
Dimension: (4, 4021)

Sentence: ['work', 'advertised', 'easy', 'setup', 'still', 'learning']
  (0, 3957)	1.0
  (1, 223)	1.0
  (2, 1188)	1.0
  (3, 3132)	1.0
  (4, 3399)	1.0
  (5, 2055)	1.0

## BOW [Just for practice, doing again in ML Pipeline]

In [63]:
#Count vectorisation for reviews_cleaned
from sklearn.feature_extraction.text import CountVectorizer
cnt_vect = CountVectorizer()
cnt_vect.fit(reviews_cleaned)
encoded_reviews_cnt_vect = cnt_vect.fit_transform(reviews_cleaned)
print("dimension:", cnt_vect.get_feature_names_out().shape[0])
print("Vocabulary:", cnt_vect.get_feature_names_out())
print(encoded_reviews_cnt_vect.toarray())

#Merging the BOW to the main data for further machine learning model building

encoded_reviews_df_bow = pd.DataFrame(encoded_reviews_cnt_vect.toarray(), columns=cnt_vect.get_feature_names_out())
final_df_cnt_bow= pd.concat([data, encoded_reviews_df_bow], axis=1)    
final_df_cnt_bow.head()

dimension: 4000
Vocabulary: ['072318' '10' '100' ... 'zzzz' 'zzzzzzz' 'útil']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

,rating,date,variation,verified_reviews,feedback,cleaned_review,072318,10,100,1000,...,youve,yr,yup,zero,zigbee,zonkedout,zwave,zzzz,zzzzzzz,útil
0,5.0,31-Jul-18,Charcoal Fabric,Love my Echo!,1.0,love echo,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5.0,31-Jul-18,Charcoal Fabric,Loved it!,1.0,loved,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1.0,sometimes playing game answer question correct...,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5.0,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1.0,lot fun thing 4 yr old learns dinosaur control...,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.0,31-Jul-18,Charcoal Fabric,Music,1.0,music,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## TF-IDF [Just for practice - doing again in ML Pipeline]

In [64]:
#TF IDF with reviews_cleaned
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer()
tfidf_vect.fit(reviews_cleaned)
encoded_reviews_tfidf_vect = tfidf_vect.fit_transform(reviews_cleaned)
print("dimension:", tfidf_vect.get_feature_names_out().shape[0])
print("Vocabulary:", tfidf_vect.get_feature_names_out())
print(encoded_reviews_tfidf_vect.toarray())

#Merging the BOW to the main data for further machine learning model building

encoded_reviews_df_tfidf = pd.DataFrame(encoded_reviews_tfidf_vect.toarray(), columns=tfidf_vect.get_feature_names_out())
final_df_cnt_tfidf= pd.concat([data,encoded_reviews_df_tfidf], axis=1)    
final_df_cnt_tfidf.head()

dimension: 4000
Vocabulary: ['072318' '10' '100' ... 'zzzz' 'zzzzzzz' 'útil']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

,rating,date,variation,verified_reviews,feedback,cleaned_review,072318,10,100,1000,...,youve,yr,yup,zero,zigbee,zonkedout,zwave,zzzz,zzzzzzz,útil
0,5.0,31-Jul-18,Charcoal Fabric,Love my Echo!,1.0,love echo,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5.0,31-Jul-18,Charcoal Fabric,Loved it!,1.0,loved,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1.0,sometimes playing game answer question correct...,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5.0,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1.0,lot fun thing 4 yr old learns dinosaur control...,0.0,0.0,0.0,0.0,...,0.0,0.327934,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.0,31-Jul-18,Charcoal Fabric,Music,1.0,music,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## ML

In [ ]:
#lets fit a logistic regression model on the count vectorised data
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

log_reg = LogisticRegression()

#test train split for the data
#60% train, 20% test, 20% validation
X_train, X_temp, y_train, y_temp = train_test_split(data['cleaned_review'], data['feedback'], test_size=0.4, random_state=42)
X_test, X_val, y_test, y_val = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42) 


#Saving the validation data for later use
data_val= pd.DataFrame({'review': X_val, 'feedback': y_val})

In [ ]:
# Name X_val a column name

                                                 review  feedback
1645  easy use answer questionshands free whats like...         1
581   bought mother love itshe love guard dog featur...         1
2334  prime day purchase im still learning way aroun...         1
3078                        love added upstairs bedroom         1
552        second dot work great refurbishedthought new         1

## ML with BOW

In [83]:
#Vectorising with BOW

from sklearn.feature_extraction.text import CountVectorizer
bow= CountVectorizer()
X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

#ML Training
log_reg.fit(X_train_bow, y_train)

probs=log_reg.predict_proba(X_test_bow)[:,1]
threshold=0.6
y_pred = (probs >= threshold).astype(int)

print(classification_report(y_test, y_pred))
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

              precision    recall  f1-score   support

           0       0.68      0.39      0.50        38
           1       0.96      0.99      0.97       575

    accuracy                           0.95       613
   macro avg       0.82      0.69      0.74       613
weighted avg       0.94      0.95      0.94       613

Confusion Matrix:
 [[ 15  23]
 [  7 568]]

## TF IDF

In [74]:

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()


X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

#ML Training
log_reg.fit(X_train_tfidf, y_train)

probs=log_reg.predict_proba(X_test_tfidf)[:,1]
threshold=0.7
y_pred = (probs >= threshold).astype(int)

print(classification_report(y_test, y_pred))
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

              precision    recall  f1-score   support

           0       0.75      0.08      0.14        38
           1       0.94      1.00      0.97       575

    accuracy                           0.94       613
   macro avg       0.85      0.54      0.56       613
weighted avg       0.93      0.94      0.92       613

Confusion Matrix:
 [[  3  35]
 [  1 574]]

## Comparison with completely new data

In [81]:
# data_val = pd.read_csv(r"D:\GEN_AI_BOOTCAMP\Live_Classes1\Assignments\Data\new_amazon_reviews.csv")
new_review_cleaned = data_val["review"].apply(preprocess_text)
new_review_cleaned = new_review_cleaned.apply(remove_punctuation)
new_review_cleaned = new_review_cleaned.apply(remove_hyphens)
Threshold_pred=0.6

#Vectorising the new review
new_review_bow= bow.transform(new_review_cleaned)   #USING TRANSFORM ONLY AS VECTORISOR IS ALREADY FITTED ON THE TRAINING DATA
new_review_tfidf = tfidf.transform(new_review_cleaned)


pred_prob_bow = log_reg.predict_proba(new_review_bow)
pred_bow= (pred_prob_bow[:, 1] >= Threshold_pred).astype(int)
pred_prob_tfidf = log_reg.predict_proba(new_review_tfidf)
pred_tfidf= (pred_prob_tfidf[:, 1] >= Threshold_pred).astype(int)

confusion_matrix_bow = confusion_matrix(data_val['feedback'], pred_bow)
confusion_matrix_tfidf = confusion_matrix(data_val['feedback'], pred_tfidf)

accuracy_bow = (confusion_matrix_bow[0, 0] + confusion_matrix_bow[1, 1]) / confusion_matrix_bow.sum()
accuracy_tfidf = (confusion_matrix_tfidf[0, 0] + confusion_matrix_tfidf[1, 1]) / confusion_matrix_tfidf.sum()

precision_bow = confusion_matrix_bow[1, 1] / (confusion_matrix_bow[0, 1] + confusion_matrix_bow[1, 1])
precision_tfidf = confusion_matrix_tfidf[1, 1] / (confusion_matrix_tfidf[0, 1] + confusion_matrix_tfidf[1, 1])

recall_bow = confusion_matrix_bow[1, 1] / (confusion_matrix_bow[1, 0] + confusion_matrix_bow[1, 1])
recall_tfidf = confusion_matrix_tfidf[1, 1] / (confusion_matrix_tfidf[1, 0] + confusion_matrix_tfidf[1, 1])

f1_score_bow = 2 * (precision_bow * recall_bow) / (precision_bow + recall_bow)
f1_score_tfidf = 2 * (precision_tfidf * recall_tfidf) / (precision_tfidf + recall_tfidf)

print("Confusion Matrix for BOW:\n", confusion_matrix_bow)
print("Confusion Matrix for TF-IDF:\n", confusion_matrix_tfidf)

print(f"Accuracy with BOW: {accuracy_bow:.2f}")
print(f"Accuracy with TF-IDF: {accuracy_tfidf:.2f}")
print(f"Precision with BOW: {precision_bow:.2f}")
print(f"Precision with TF-IDF: {precision_tfidf:.2f}")
print(f"Recall with BOW: {recall_bow:.2f}")
print(f"Recall with TF-IDF: {recall_tfidf:.2f}")
print(f"F1 Score with BOW: {f1_score_bow:.2f}")
print(f"F1 Score with TF-IDF: {f1_score_tfidf:.2f}")

#Merge the predictions with the main data
data_val["predicted_label_bow"] = pred_bow
data_val["predicted_label_tfidf"] = pred_tfidf
data_val["predicted_prob_bow"] = pred_prob_bow[:, 1]
data_val["predicted_prob_tfidf"] = pred_prob_tfidf[:, 1]
data_val.head()

Confusion Matrix for BOW:
 [[ 22  31]
 [ 15 545]]
Confusion Matrix for TF-IDF:
 [[  1  52]
 [  0 560]]
Accuracy with BOW: 0.92
Accuracy with TF-IDF: 0.92
Precision with BOW: 0.95
Precision with TF-IDF: 0.92
Recall with BOW: 0.97
Recall with TF-IDF: 1.00
F1 Score with BOW: 0.96
F1 Score with TF-IDF: 0.96

,review,feedback,predicted_label_bow,predicted_label_tfidf,predicted_prob_bow,predicted_prob_tfidf
1645,easy use answer questionshands free whats like...,1,1,1,0.978474,0.906733
581,bought mother love itshe love guard dog featur...,1,1,1,0.999981,0.968189
2334,prime day purchase im still learning way aroun...,1,1,1,0.997035,0.957920
3078,love added upstairs bedroom,1,1,1,0.998222,0.963610
552,second dot work great refurbishedthought new,1,1,1,0.992298,0.954631

In [82]:
# EXPORT TO EXCEL
data_val.to_excel(r"D:\GEN_AI_BOOTCAMP\Live_Classes1\Assignments\Data\alexa_reviews_with_predictions.xlsx", index=False)