In [2]:
print("this is assignment for text vectorisation")

this is assignment for text vectorisation

## Assignment
- Reading the data - in this example synthetic data has been used
- Text Preprocessing
- One hot encoding
- BoW
- TF- IDF
- ML

## Reading the data

In [3]:
#Reading the data
import pandas as pd
data = pd.read_csv("D:\GEN_AI_BOOTCAMP\Live_Classes1\Assignments\Data\enriched_amazon_reviews.csv")
data.head()

                                              review  label
0  Customer service was no help when the t-shirt ...      0
1        The pair of jeans is slow and unresponsive.      0
2        The air fryer is too noisy and inefficient.      0
3  The air fryer is disappointing, although it do...      0
4      The smartphone doesn’t match the description.      0

In [4]:
#Converting the reviews in list of sentence
reviews = data["review"].tolist()
reviews[:5]

['Customer service was no help when the t-shirt broke.',
 'The pair of jeans is slow and unresponsive.',
 'The air fryer is too noisy and inefficient.',
 'The air fryer is disappointing, although it does look nice.',
 'The smartphone doesn’t match the description.']

## Text Preprocessing

In [5]:
#Text preprocessing including lowercasing, removing punctuation and stop words,stopwords,lametisation
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# nltk.download("stopwords")
# nltk.download("wordnet")
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return " ".join(lemmatized_tokens)
preprocessed_reviews = [preprocess_text(review) for review in reviews]

#Removing Punctuation
import string
def remove_punctuation(text):
    return text.translate(str.maketrans("", "", string.punctuation))
reviews_cleaned = [remove_punctuation(review) for review in preprocessed_reviews]


#remove hyphens
def remove_hyphens(text):
    return text.replace("-", " ")
reviews_cleaned = [remove_hyphens(review) for review in reviews_cleaned]
reviews_cleaned[:5]

['customer service help tshirt broke',
 'pair jean slow unresponsive',
 'air fryer noisy inefficient',
 'air fryer disappointing although look nice',
 'smartphone doesnt match description']

In [6]:
#Need to merge the cleaned reviews with the main dataframe
data["cleaned_review"] = reviews_cleaned
data.head()

,review,label,cleaned_review
0,Customer service was no help when the t-shirt ...,0,customer service help tshirt broke
1,The pair of jeans is slow and unresponsive.,0,pair jean slow unresponsive
2,The air fryer is too noisy and inefficient.,0,air fryer noisy inefficient
3,"The air fryer is disappointing, although it do...",0,air fryer disappointing although look nice
4,The smartphone doesn’t match the description.,0,smartphone doesnt match description

## Tokenisation

In [7]:
#Tokenisation of reviews_cleaned
tokenized_reviews = [review.split() for review in reviews_cleaned]

In [8]:
#Specific format
all_words = [[word] for review in tokenized_reviews for word in review]
all_words[:5]

[['customer'], ['service'], ['help'], ['tshirt'], ['broke']]

## One hot encoding

In [9]:

#fit one hot encoding
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
encoder.fit(all_words)
print("Vocabulary:", encoder.categories_[0])
encoder.categories_[0].shape

Vocabulary: ['absolutely' 'affordable' 'air' 'already' 'although' 'amazing' 'anyone'
 'arrived' 'battery' 'best' 'biography' 'bit' 'blender' 'bluetooth' 'book'
 'broke' 'bulky' 'buying' 'came' 'changer' 'cheap' 'clean' 'clearer'
 'coffee' 'color' 'comfortable' 'compact' 'compliment' 'cookbook' 'could'
 'customer' 'damaged' 'day' 'description' 'design' 'didnt' 'disappointed'
 'disappointing' 'disappoints' 'doesnt' 'dress' 'easier' 'easy'
 'effective' 'efficient' 'especially' 'ever' 'every' 'exceeded'
 'excellent' 'expectation' 'fantastic' 'fast' 'feature' 'feel' 'first'
 'fit' 'flawlessly' 'friend' 'fryer' 'game' 'great' 'hard' 'headphone'
 'help' 'high' 'highly' 'hope' 'impressive' 'inefficient' 'instruction'
 'intuitive' 'ive' 'jacket' 'jean' 'kitchen' 'knife' 'laptop' 'lasted'
 'late' 'least' 'let' 'life' 'lightweight' 'longer' 'look' 'looking'
 'love' 'made' 'maintain' 'maker' 'many' 'match' 'meet' 'missing' 'money'
 'much' 'never' 'nice' 'noisy' 'novel' 'offer' 'one' 'overall' 'overheats'
 'overpriced' 'owned' 'packaging' 'pair' 'part' 'penny' 'perfectly'
 'performance' 'performs' 'poor' 'poorly' 'price' 'pricey' 'quality'
 'quickly' 'received' 'recommend' 'recommended' 'regret' 'reliable'
 'return' 'selfhelp' 'service' 'set' 'setup' 'shipping' 'skeptical'
 'sleek' 'slow' 'smartphone' 'smell' 'sneaker' 'speaker' 'stopped' 'store'
 'stylish' 'tablet' 'terrible' 'textbook' 'though' 'time' 'toaster'
 'tricky' 'tshirt' 'turned' 'uncomfortable' 'unresponsive' 'unsafe' 'use'
 'used' 'userfriendly' 'value' 'week' 'weird' 'well' 'wellbuilt' 'wish'
 'work' 'working' 'worth']

(165,)

In [21]:
#One hot encoding for reviews cleaned
import numpy as np
for sentence in tokenized_reviews:
    # print (np.array(sentence))
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print(encoded_sentence)
    print("Dimension:", encoded_sentence.shape)

Sentence: ['customer', 'service', 'help', 'tshirt', 'broke']
  (0, 30)	1.0
  (1, 127)	1.0
  (2, 64)	1.0
  (3, 148)	1.0
  (4, 15)	1.0
Dimension: (5, 165)

Sentence: ['pair', 'jean', 'slow', 'unresponsive']
  (0, 108)	1.0
  (1, 74)	1.0
  (2, 133)	1.0
  (3, 151)	1.0
Dimension: (4, 165)

Sentence: ['air', 'fryer', 'noisy', 'inefficient']
  (0, 2)	1.0
  (1, 59)	1.0
  (2, 99)	1.0
  (3, 69)	1.0
Dimension: (4, 165)

Sentence: ['air', 'fryer', 'disappointing', 'although', 'look', 'nice']
  (0, 2)	1.0
  (1, 59)	1.0
  (2, 37)	1.0
  (3, 4)	1.0
  (4, 85)	1.0
  (5, 98)	1.0
Dimension: (6, 165)

Sentence: ['smartphone', 'doesnt', 'match', 'description']
  (0, 134)	1.0
  (1, 39)	1.0
  (2, 92)	1.0
  (3, 33)	1.0
Dimension: (4, 165)

Sentence: ['sneaker', 'noisy', 'inefficient']
  (0, 136)	1.0
  (1, 99)	1.0
  (2, 69)	1.0
Dimension: (3, 165)

Sentence: ['smartphone', 'great', 'packaging', 'damaged']
  (0, 134)	1.0
  (1, 61)	1.0
  (2, 107)	1.0
  (3, 31)	1.0
Dimension: (4, 165)

Sentence: ['laptop', 'intuitive', 'userfriendly']
  (0, 77)	1.0
  (1, 71)	1.0
  (2, 155)	1.0
Dimension: (3, 165)

Sentence: ['cookbook', 'performs', 'well', 'wish', 'battery', 'lasted', 'longer']
  (0, 28)	1.0
  (1, 113)	1.0
  (2, 159)	1.0
  (3, 161)	1.0
  (4, 8)	1.0
  (5, 78)	1.0
  (6, 84)	1.0
Dimension: (7, 165)

Sentence: ['tablet', 'work', 'great', 'overall', 'though', 'setup', 'bit', 'tricky']
  (0, 141)	1.0
  (1, 162)	1.0
  (2, 61)	1.0
  (3, 103)	1.0
  (4, 144)	1.0
  (5, 129)	1.0
  (6, 11)	1.0
  (7, 147)	1.0
Dimension: (8, 165)

Sentence: ['customer', 'service', 'help', 'novel', 'broke']
  (0, 30)	1.0
  (1, 127)	1.0
  (2, 64)	1.0
  (3, 100)	1.0
  (4, 15)	1.0
Dimension: (5, 165)

Sentence: ['pair', 'jean', 'arrived', 'late', 'damaged']
  (0, 108)	1.0
  (1, 74)	1.0
  (2, 7)	1.0
  (3, 79)	1.0
  (4, 31)	1.0
Dimension: (5, 165)

Sentence: ['tablet', 'arrived', 'time', 'performs', 'perfectly']
  (0, 141)	1.0
  (1, 7)	1.0
  (2, 145)	1.0
  (3, 113)	1.0
  (4, 111)	1.0
Dimension: (5, 165)

Sentence: ['toaster', 'stopped', 'working', 'week']
  (0, 146)	1.0
  (1, 138)	1.0
  (2, 163)	1.0
  (3, 157)	1.0
Dimension: (4, 165)

Sentence: ['knife', 'set', 'made', 'life', 'much', 'easier']
  (0, 76)	1.0
  (1, 128)	1.0
  (2, 88)	1.0
  (3, 82)	1.0
  (4, 96)	1.0
  (5, 41)	1.0
Dimension: (6, 165)

Sentence: ['battery', 'life', 'air', 'fryer', 'terrible']
  (0, 8)	1.0
  (1, 82)	1.0
  (2, 2)	1.0
  (3, 59)	1.0
  (4, 142)	1.0
Dimension: (5, 165)

Sentence: ['knife', 'set', 'overpriced', 'offer']
  (0, 76)	1.0
  (1, 128)	1.0
  (2, 105)	1.0
  (3, 101)	1.0
Dimension: (4, 165)

Sentence: ['blender', 'bulky', 'hard', 'store']
  (0, 12)	1.0
  (1, 16)	1.0
  (2, 62)	1.0
  (3, 139)	1.0
Dimension: (4, 165)

Sentence: ['sneaker', 'overheats', 'quickly', 'unsafe']
  (0, 136)	1.0
  (1, 104)	1.0
  (2, 119)	1.0
  (3, 152)	1.0
Dimension: (4, 165)

Sentence: ['tablet', 'weird', 'smell', 'feel', 'used']
  (0, 141)	1.0
  (1, 158)	1.0
  (2, 135)	1.0
  (3, 54)	1.0
  (4, 154)	1.0
Dimension: (5, 165)

Sentence: ['love', 'cookbook', 'instruction', 'could', 'clearer']
  (0, 87)	1.0
  (1, 28)	1.0
  (2, 70)	1.0
  (3, 29)	1.0
  (4, 22)	1.0
Dimension: (5, 165)

Sentence: ['smartphone', 'performs', 'well', 'wish', 'battery', 'lasted', 'longer']
  (0, 134)	1.0
  (1, 113)	1.0
  (2, 159)	1.0
  (3, 161)	1.0
  (4, 8)	1.0
  (5, 78)	1.0
  (6, 84)	1.0
Dimension: (7, 165)

Sentence: ['tshirt', 'feel', 'cheap', 'poorly', 'made']
  (0, 148)	1.0
  (1, 54)	1.0
  (2, 20)	1.0
  (3, 115)	1.0
  (4, 88)	1.0
Dimension: (5, 165)

Sentence: ['absolutely', 'love', 'textbook', 'exceeded', 'expectation']
  (0, 0)	1.0
  (1, 87)	1.0
  (2, 143)	1.0
  (3, 48)	1.0
  (4, 50)	1.0
Dimension: (5, 165)

Sentence: ['selfhelp', 'book', 'noisy', 'inefficient']
  (0, 126)	1.0
  (1, 14)	1.0
  (2, 99)	1.0
  (3, 69)	1.0
Dimension: (4, 165)

Sentence: ['knife', 'set', 'lightweight', 'fit', 'perfectly']
  (0, 76)	1.0
  (1, 128)	1.0
  (2, 83)	1.0
  (3, 56)	1.0
  (4, 111)	1.0
Dimension: (5, 165)

Sentence: ['air', 'fryer', 'performs', 'well', 'wish', 'battery', 'lasted', 'longer']
  (0, 2)	1.0
  (1, 59)	1.0
  (2, 113)	1.0
  (3, 159)	1.0
  (4, 161)	1.0
  (5, 8)	1.0
  (6, 78)	1.0
  (7, 84)	1.0
Dimension: (8, 165)

Sentence: ['jacket', 'userfriendly']
  (0, 73)	1.0
  (1, 155)	1.0
Dimension: (2, 165)

Sentence: ['coffee', 'maker', 'performs', 'well', 'wish', 'battery', 'lasted', 'longer']
  (0, 23)	1.0
  (1, 90)	1.0
  (2, 113)	1.0
  (3, 159)	1.0
  (4, 161)	1.0
  (5, 8)	1.0
  (6, 78)	1.0
  (7, 84)	1.0
Dimension: (8, 165)

Sentence: ['skeptical', 'first', 'coffee', 'maker', 'turned', 'amazing']
  (0, 131)	1.0
  (1, 55)	1.0
  (2, 23)	1.0
  (3, 90)	1.0
  (4, 149)	1.0
  (5, 5)	1.0
Dimension: (6, 165)

Sentence: ['ive', 'already', 'recommended', 'pair', 'jean', 'friend']
  (0, 72)	1.0
  (1, 3)	1.0
  (2, 122)	1.0
  (3, 108)	1.0
  (4, 74)	1.0
  (5, 58)	1.0
Dimension: (6, 165)

Sentence: ['tshirt', 'overpriced', 'offer']
  (0, 148)	1.0
  (1, 105)	1.0
  (2, 101)	1.0
Dimension: (3, 165)

Sentence: ['regret', 'buying', 'textbook']
  (0, 123)	1.0
  (1, 17)	1.0
  (2, 143)	1.0
Dimension: (3, 165)

Sentence: ['novel', 'compact', 'efficient', 'look', 'great', 'kitchen']
  (0, 100)	1.0
  (1, 26)	1.0
  (2, 44)	1.0
  (3, 85)	1.0
  (4, 61)	1.0
  (5, 75)	1.0
Dimension: (6, 165)

Sentence: ['jacket', 'weird', 'smell', 'feel', 'used']
  (0, 73)	1.0
  (1, 158)	1.0
  (2, 135)	1.0
  (3, 54)	1.0
  (4, 154)	1.0
Dimension: (5, 165)

Sentence: ['tshirt', 'fantastic', 'although', 'bit', 'pricey']
  (0, 148)	1.0
  (1, 51)	1.0
  (2, 4)	1.0
  (3, 11)	1.0
  (4, 117)	1.0
Dimension: (5, 165)

Sentence: ['cookbook', 'game', 'changer']
  (0, 28)	1.0
  (1, 60)	1.0
  (2, 19)	1.0
Dimension: (3, 165)

Sentence: ['cookbook', 'feel', 'cheap', 'poorly', 'made']
  (0, 28)	1.0
  (1, 54)	1.0
  (2, 20)	1.0
  (3, 115)	1.0
  (4, 88)	1.0
Dimension: (5, 165)

Sentence: ['toaster', 'made', 'life', 'much', 'easier']
  (0, 146)	1.0
  (1, 88)	1.0
  (2, 82)	1.0
  (3, 96)	1.0
  (4, 41)	1.0
Dimension: (5, 165)

Sentence: ['textbook', 'noisy', 'inefficient']
  (0, 143)	1.0
  (1, 99)	1.0
  (2, 69)	1.0
Dimension: (3, 165)

Sentence: ['ive', 'received', 'many', 'compliment', 'selfhelp', 'book']
  (0, 72)	1.0
  (1, 120)	1.0
  (2, 91)	1.0
  (3, 27)	1.0
  (4, 126)	1.0
  (5, 14)	1.0
Dimension: (6, 165)

Sentence: ['pair', 'jean', 'arrived', 'late', 'damaged']
  (0, 108)	1.0
  (1, 74)	1.0
  (2, 7)	1.0
  (3, 79)	1.0
  (4, 31)	1.0
Dimension: (5, 165)

Sentence: ['headphone', 'fantastic', 'although', 'bit', 'pricey']
  (0, 63)	1.0
  (1, 51)	1.0
  (2, 4)	1.0
  (3, 11)	1.0
  (4, 117)	1.0
Dimension: (5, 165)

Sentence: ['dress', 'uncomfortable', 'color', 'nice']
  (0, 40)	1.0
  (1, 150)	1.0
  (2, 24)	1.0
  (3, 98)	1.0
Dimension: (4, 165)

Sentence: ['battery', 'life', 'blender', 'terrible']
  (0, 8)	1.0
  (1, 82)	1.0
  (2, 12)	1.0
  (3, 142)	1.0
Dimension: (4, 165)

Sentence: ['effective', 'bluetooth', 'speaker', 'least', 'affordable']
  (0, 43)	1.0
  (1, 13)	1.0
  (2, 137)	1.0
  (3, 80)	1.0
  (4, 1)	1.0
Dimension: (5, 165)

Sentence: ['battery', 'life', 'pair', 'jean', 'terrible']
  (0, 8)	1.0
  (1, 82)	1.0
  (2, 108)	1.0
  (3, 74)	1.0
  (4, 142)	1.0
Dimension: (5, 165)

Sentence: ['blender', 'arrived', 'late', 'damaged']
  (0, 12)	1.0
  (1, 7)	1.0
  (2, 79)	1.0
  (3, 31)	1.0
Dimension: (4, 165)

Sentence: ['novel', 'made', 'life', 'much', 'easier']
  (0, 100)	1.0
  (1, 88)	1.0
  (2, 82)	1.0
  (3, 96)	1.0
  (4, 41)	1.0
Dimension: (5, 165)

Sentence: ['jacket', 'bulky', 'hard', 'store']
  (0, 73)	1.0
  (1, 16)	1.0
  (2, 62)	1.0
  (3, 139)	1.0
Dimension: (4, 165)

Sentence: ['cookbook', 'intuitive', 'userfriendly']
  (0, 28)	1.0
  (1, 71)	1.0
  (2, 155)	1.0
Dimension: (3, 165)

Sentence: ['hard', 'clean', 'maintain', 'sneaker']
  (0, 62)	1.0
  (1, 21)	1.0
  (2, 89)	1.0
  (3, 136)	1.0
Dimension: (4, 165)

Sentence: ['coffee', 'maker', 'arrived', 'time', 'performs', 'perfectly']
  (0, 23)	1.0
  (1, 90)	1.0
  (2, 7)	1.0
  (3, 145)	1.0
  (4, 113)	1.0
  (5, 111)	1.0
Dimension: (6, 165)

Sentence: ['knife', 'set', 'overheats', 'quickly', 'unsafe']
  (0, 76)	1.0
  (1, 128)	1.0
  (2, 104)	1.0
  (3, 119)	1.0
  (4, 152)	1.0
Dimension: (5, 165)

Sentence: ['jacket', 'stopped', 'working', 'week']
  (0, 73)	1.0
  (1, 138)	1.0
  (2, 163)	1.0
  (3, 157)	1.0
Dimension: (4, 165)

Sentence: ['battery', 'life', 'smartphone', 'impressive']
  (0, 8)	1.0
  (1, 82)	1.0
  (2, 134)	1.0
  (3, 68)	1.0
Dimension: (4, 165)

Sentence: ['effective', 'dress', 'least', 'affordable']
  (0, 43)	1.0
  (1, 40)	1.0
  (2, 80)	1.0
  (3, 1)	1.0
Dimension: (4, 165)

Sentence: ['customer', 'service', 'help', 'air', 'fryer', 'broke']
  (0, 30)	1.0
  (1, 127)	1.0
  (2, 64)	1.0
  (3, 2)	1.0
  (4, 59)	1.0
  (5, 15)	1.0
Dimension: (6, 165)

Sentence: ['knife', 'set', 'wellbuilt', 'easy', 'use']
  (0, 76)	1.0
  (1, 128)	1.0
  (2, 160)	1.0
  (3, 42)	1.0
  (4, 153)	1.0
Dimension: (5, 165)

Sentence: ['coffee', 'maker', 'performs', 'well', 'wish', 'battery', 'lasted', 'longer']
  (0, 23)	1.0
  (1, 90)	1.0
  (2, 113)	1.0
  (3, 159)	1.0
  (4, 161)	1.0
  (5, 8)	1.0
  (6, 78)	1.0
  (7, 84)	1.0
Dimension: (8, 165)

Sentence: ['dress', 'noisy', 'inefficient']
  (0, 40)	1.0
  (1, 99)	1.0
  (2, 69)	1.0
Dimension: (3, 165)

Sentence: ['smartphone', 'disappointing', 'although', 'look', 'nice']
  (0, 134)	1.0
  (1, 37)	1.0
  (2, 4)	1.0
  (3, 85)	1.0
  (4, 98)	1.0
Dimension: (5, 165)

Sentence: ['biography', 'disappointing', 'although', 'look', 'nice']
  (0, 10)	1.0
  (1, 37)	1.0
  (2, 4)	1.0
  (3, 85)	1.0
  (4, 98)	1.0
Dimension: (5, 165)

Sentence: ['smartphone', 'bulky', 'hard', 'store']
  (0, 134)	1.0
  (1, 16)	1.0
  (2, 62)	1.0
  (3, 139)	1.0
Dimension: (4, 165)

Sentence: ['fantastic', 'smartphone', 'especially', 'price']
  (0, 51)	1.0
  (1, 134)	1.0
  (2, 45)	1.0
  (3, 116)	1.0
Dimension: (4, 165)

Sentence: ['disappointed', 'cookbook', 'worth', 'money']
  (0, 36)	1.0
  (1, 28)	1.0
  (2, 164)	1.0
  (3, 95)	1.0
Dimension: (4, 165)

Sentence: ['high', 'hope', 'novel', 'let']
  (0, 65)	1.0
  (1, 67)	1.0
  (2, 100)	1.0
  (3, 81)	1.0
Dimension: (4, 165)

Sentence: ['air', 'fryer', 'fantastic', 'although', 'bit', 'pricey']
  (0, 2)	1.0
  (1, 59)	1.0
  (2, 51)	1.0
  (3, 4)	1.0
  (4, 11)	1.0
  (5, 117)	1.0
Dimension: (6, 165)

Sentence: ['selfhelp', 'book', 'game', 'changer']
  (0, 126)	1.0
  (1, 14)	1.0
  (2, 60)	1.0
  (3, 19)	1.0
Dimension: (4, 165)

Sentence: ['sneaker', 'fantastic', 'although', 'bit', 'pricey']
  (0, 136)	1.0
  (1, 51)	1.0
  (2, 4)	1.0
  (3, 11)	1.0
  (4, 117)	1.0
Dimension: (5, 165)

Sentence: ['hard', 'clean', 'maintain', 'headphone']
  (0, 62)	1.0
  (1, 21)	1.0
  (2, 89)	1.0
  (3, 63)	1.0
Dimension: (4, 165)

Sentence: ['effective', 'headphone', 'least', 'affordable']
  (0, 43)	1.0
  (1, 63)	1.0
  (2, 80)	1.0
  (3, 1)	1.0
Dimension: (4, 165)

Sentence: ['blender', 'didnt', 'meet', 'expectation', 'shipping', 'fast']
  (0, 12)	1.0
  (1, 35)	1.0
  (2, 93)	1.0
  (3, 50)	1.0
  (4, 130)	1.0
  (5, 52)	1.0
Dimension: (6, 165)

Sentence: ['dress', 'arrived', 'time', 'performs', 'perfectly']
  (0, 40)	1.0
  (1, 7)	1.0
  (2, 145)	1.0
  (3, 113)	1.0
  (4, 111)	1.0
Dimension: (5, 165)

Sentence: ['customer', 'service', 'help', 'sneaker', 'broke']
  (0, 30)	1.0
  (1, 127)	1.0
  (2, 64)	1.0
  (3, 136)	1.0
  (4, 15)	1.0
Dimension: (5, 165)

Sentence: ['use', 'pair', 'jean', 'every', 'day', 'never', 'disappoints']
  (0, 153)	1.0
  (1, 108)	1.0
  (2, 74)	1.0
  (3, 47)	1.0
  (4, 32)	1.0
  (5, 97)	1.0
  (6, 38)	1.0
Dimension: (7, 165)

Sentence: ['use', 'knife', 'set', 'every', 'day', 'never', 'disappoints']
  (0, 153)	1.0
  (1, 76)	1.0
  (2, 128)	1.0
  (3, 47)	1.0
  (4, 32)	1.0
  (5, 97)	1.0
  (6, 38)	1.0
Dimension: (7, 165)

Sentence: ['knife', 'set', 'arrived', 'time', 'performs', 'perfectly']
  (0, 76)	1.0
  (1, 128)	1.0
  (2, 7)	1.0
  (3, 145)	1.0
  (4, 113)	1.0
  (5, 111)	1.0
Dimension: (6, 165)

Sentence: ['skeptical', 'first', 'dress', 'turned', 'amazing']
  (0, 131)	1.0
  (1, 55)	1.0
  (2, 40)	1.0
  (3, 149)	1.0
  (4, 5)	1.0
Dimension: (5, 165)

Sentence: ['novel', 'noisy', 'inefficient']
  (0, 100)	1.0
  (1, 99)	1.0
  (2, 69)	1.0
Dimension: (3, 165)

Sentence: ['effective', 'selfhelp', 'book', 'least', 'affordable']
  (0, 43)	1.0
  (1, 126)	1.0
  (2, 14)	1.0
  (3, 80)	1.0
  (4, 1)	1.0
Dimension: (5, 165)

Sentence: ['best', 'toaster', 'ive', 'ever', 'owned']
  (0, 9)	1.0
  (1, 146)	1.0
  (2, 72)	1.0
  (3, 46)	1.0
  (4, 106)	1.0
Dimension: (5, 165)

Sentence: ['tablet', 'noisy', 'inefficient']
  (0, 141)	1.0
  (1, 99)	1.0
  (2, 69)	1.0
Dimension: (3, 165)

Sentence: ['jacket', 'bulky', 'hard', 'store']
  (0, 73)	1.0
  (1, 16)	1.0
  (2, 62)	1.0
  (3, 139)	1.0
Dimension: (4, 165)

Sentence: ['fantastic', 'selfhelp', 'book', 'especially', 'price']
  (0, 51)	1.0
  (1, 126)	1.0
  (2, 14)	1.0
  (3, 45)	1.0
  (4, 116)	1.0
Dimension: (5, 165)

Sentence: ['jacket', 'work', 'great', 'overall', 'though', 'setup', 'bit', 'tricky']
  (0, 73)	1.0
  (1, 162)	1.0
  (2, 61)	1.0
  (3, 103)	1.0
  (4, 144)	1.0
  (5, 129)	1.0
  (6, 11)	1.0
  (7, 147)	1.0
Dimension: (8, 165)

Sentence: ['cookbook', 'uncomfortable', 'color', 'nice']
  (0, 28)	1.0
  (1, 150)	1.0
  (2, 24)	1.0
  (3, 98)	1.0
Dimension: (4, 165)

Sentence: ['air', 'fryer', 'noisy', 'inefficient']
  (0, 2)	1.0
  (1, 59)	1.0
  (2, 99)	1.0
  (3, 69)	1.0
Dimension: (4, 165)

Sentence: ['laptop', 'compact', 'efficient', 'look', 'great', 'kitchen']
  (0, 77)	1.0
  (1, 26)	1.0
  (2, 44)	1.0
  (3, 85)	1.0
  (4, 61)	1.0
  (5, 75)	1.0
Dimension: (6, 165)

Sentence: ['poor', 'performance', 'though', 'air', 'fryer', 'design', 'sleek']
  (0, 114)	1.0
  (1, 112)	1.0
  (2, 144)	1.0
  (3, 2)	1.0
  (4, 59)	1.0
  (5, 34)	1.0
  (6, 132)	1.0
Dimension: (7, 165)

Sentence: ['sneaker', 'userfriendly']
  (0, 136)	1.0
  (1, 155)	1.0
Dimension: (2, 165)

Sentence: ['textbook', 'overpriced', 'offer']
  (0, 143)	1.0
  (1, 105)	1.0
  (2, 101)	1.0
Dimension: (3, 165)

Sentence: ['great', 'value', 'price', 'headphone', 'worth', 'every', 'penny']
  (0, 61)	1.0
  (1, 156)	1.0
  (2, 116)	1.0
  (3, 63)	1.0
  (4, 164)	1.0
  (5, 47)	1.0
  (6, 110)	1.0
Dimension: (7, 165)

Sentence: ['ive', 'already', 'recommended', 'cookbook', 'friend']
  (0, 72)	1.0
  (1, 3)	1.0
  (2, 122)	1.0
  (3, 28)	1.0
  (4, 58)	1.0
Dimension: (5, 165)

Sentence: ['cookbook', 'feel', 'cheap', 'poorly', 'made']
  (0, 28)	1.0
  (1, 54)	1.0
  (2, 20)	1.0
  (3, 115)	1.0
  (4, 88)	1.0
Dimension: (5, 165)

Sentence: ['disappointed', 'pair', 'jean', 'worth', 'money']
  (0, 36)	1.0
  (1, 108)	1.0
  (2, 74)	1.0
  (3, 164)	1.0
  (4, 95)	1.0
Dimension: (5, 165)

Sentence: ['headphone', 'noisy', 'inefficient']
  (0, 63)	1.0
  (1, 99)	1.0
  (2, 69)	1.0
Dimension: (3, 165)

Sentence: ['disappointed', 'jacket', 'worth', 'money']
  (0, 36)	1.0
  (1, 73)	1.0
  (2, 164)	1.0
  (3, 95)	1.0
Dimension: (4, 165)

Sentence: ['laptop', 'compact', 'efficient', 'look', 'great', 'kitchen']
  (0, 77)	1.0
  (1, 26)	1.0
  (2, 44)	1.0
  (3, 85)	1.0
  (4, 61)	1.0
  (5, 75)	1.0
Dimension: (6, 165)

Sentence: ['cookbook', 'fantastic', 'although', 'bit', 'pricey']
  (0, 28)	1.0
  (1, 51)	1.0
  (2, 4)	1.0
  (3, 11)	1.0
  (4, 117)	1.0
Dimension: (5, 165)

Sentence: ['absolutely', 'love', 'bluetooth', 'speaker', 'exceeded', 'expectation']
  (0, 0)	1.0
  (1, 87)	1.0
  (2, 13)	1.0
  (3, 137)	1.0
  (4, 48)	1.0
  (5, 50)	1.0
Dimension: (6, 165)

Sentence: ['toaster', 'noisy', 'inefficient']
  (0, 146)	1.0
  (1, 99)	1.0
  (2, 69)	1.0
Dimension: (3, 165)

Sentence: ['use', 'selfhelp', 'book', 'every', 'day', 'never', 'disappoints']
  (0, 153)	1.0
  (1, 126)	1.0
  (2, 14)	1.0
  (3, 47)	1.0
  (4, 32)	1.0
  (5, 97)	1.0
  (6, 38)	1.0
Dimension: (7, 165)

Sentence: ['laptop', 'came', 'missing', 'part']
  (0, 77)	1.0
  (1, 18)	1.0
  (2, 94)	1.0
  (3, 109)	1.0
Dimension: (4, 165)

Sentence: ['sneaker', 'slow', 'unresponsive']
  (0, 136)	1.0
  (1, 133)	1.0
  (2, 151)	1.0
Dimension: (3, 165)

Sentence: ['customer', 'service', 'help', 'selfhelp', 'book', 'broke']
  (0, 30)	1.0
  (1, 127)	1.0
  (2, 64)	1.0
  (3, 126)	1.0
  (4, 14)	1.0
  (5, 15)	1.0
Dimension: (6, 165)

Sentence: ['tshirt', 'work', 'great', 'overall', 'though', 'setup', 'bit', 'tricky']
  (0, 148)	1.0
  (1, 162)	1.0
  (2, 61)	1.0
  (3, 103)	1.0
  (4, 144)	1.0
  (5, 129)	1.0
  (6, 11)	1.0
  (7, 147)	1.0
Dimension: (8, 165)

Sentence: ['dress', 'intuitive', 'userfriendly']
  (0, 40)	1.0
  (1, 71)	1.0
  (2, 155)	1.0
Dimension: (3, 165)

Sentence: ['selfhelp', 'book', 'disappointing', 'although', 'look', 'nice']
  (0, 126)	1.0
  (1, 14)	1.0
  (2, 37)	1.0
  (3, 4)	1.0
  (4, 85)	1.0
  (5, 98)	1.0
Dimension: (6, 165)

Sentence: ['smartphone', 'uncomfortable', 'look', 'cheap']
  (0, 134)	1.0
  (1, 150)	1.0
  (2, 85)	1.0
  (3, 20)	1.0
Dimension: (4, 165)

Sentence: ['great', 'value', 'price', 'laptop', 'worth', 'every', 'penny']
  (0, 61)	1.0
  (1, 156)	1.0
  (2, 116)	1.0
  (3, 77)	1.0
  (4, 164)	1.0
  (5, 47)	1.0
  (6, 110)	1.0
Dimension: (7, 165)

Sentence: ['ive', 'already', 'recommended', 'dress', 'friend']
  (0, 72)	1.0
  (1, 3)	1.0
  (2, 122)	1.0
  (3, 40)	1.0
  (4, 58)	1.0
Dimension: (5, 165)

Sentence: ['return', 'dress', 'one', 'use']
  (0, 125)	1.0
  (1, 40)	1.0
  (2, 102)	1.0
  (3, 153)	1.0
Dimension: (4, 165)

Sentence: ['ive', 'received', 'many', 'compliment', 'tablet']
  (0, 72)	1.0
  (1, 120)	1.0
  (2, 91)	1.0
  (3, 27)	1.0
  (4, 141)	1.0
Dimension: (5, 165)

Sentence: ['novel', 'slow', 'unresponsive']
  (0, 100)	1.0
  (1, 133)	1.0
  (2, 151)	1.0
Dimension: (3, 165)

Sentence: ['dress', 'noisy', 'inefficient']
  (0, 40)	1.0
  (1, 99)	1.0
  (2, 69)	1.0
Dimension: (3, 165)

Sentence: ['sneaker', 'great', 'packaging', 'damaged']
  (0, 136)	1.0
  (1, 61)	1.0
  (2, 107)	1.0
  (3, 31)	1.0
Dimension: (4, 165)

Sentence: ['knife', 'set', 'great', 'packaging', 'damaged']
  (0, 76)	1.0
  (1, 128)	1.0
  (2, 61)	1.0
  (3, 107)	1.0
  (4, 31)	1.0
Dimension: (5, 165)

Sentence: ['cookbook', 'userfriendly']
  (0, 28)	1.0
  (1, 155)	1.0
Dimension: (2, 165)

Sentence: ['skeptical', 'first', 'tablet', 'turned', 'amazing']
  (0, 131)	1.0
  (1, 55)	1.0
  (2, 141)	1.0
  (3, 149)	1.0
  (4, 5)	1.0
Dimension: (5, 165)

Sentence: ['highly', 'recommend', 'sneaker', 'anyone', 'looking', 'quality']
  (0, 66)	1.0
  (1, 121)	1.0
  (2, 136)	1.0
  (3, 6)	1.0
  (4, 86)	1.0
  (5, 118)	1.0
Dimension: (6, 165)

Sentence: ['knife', 'set', 'great', 'packaging', 'damaged']
  (0, 76)	1.0
  (1, 128)	1.0
  (2, 61)	1.0
  (3, 107)	1.0
  (4, 31)	1.0
Dimension: (5, 165)

Sentence: ['sneaker', 'didnt', 'meet', 'expectation', 'shipping', 'fast']
  (0, 136)	1.0
  (1, 35)	1.0
  (2, 93)	1.0
  (3, 50)	1.0
  (4, 130)	1.0
  (5, 52)	1.0
Dimension: (6, 165)

Sentence: ['knife', 'set', 'didnt', 'meet', 'expectation', 'shipping', 'fast']
  (0, 76)	1.0
  (1, 128)	1.0
  (2, 35)	1.0
  (3, 93)	1.0
  (4, 50)	1.0
  (5, 130)	1.0
  (6, 52)	1.0
Dimension: (7, 165)

Sentence: ['ive', 'received', 'many', 'compliment', 'coffee', 'maker']
  (0, 72)	1.0
  (1, 120)	1.0
  (2, 91)	1.0
  (3, 27)	1.0
  (4, 23)	1.0
  (5, 90)	1.0
Dimension: (6, 165)

Sentence: ['pair', 'jean', 'great', 'packaging', 'damaged']
  (0, 108)	1.0
  (1, 74)	1.0
  (2, 61)	1.0
  (3, 107)	1.0
  (4, 31)	1.0
Dimension: (5, 165)

Sentence: ['textbook', 'compact', 'efficient', 'look', 'great', 'kitchen']
  (0, 143)	1.0
  (1, 26)	1.0
  (2, 44)	1.0
  (3, 85)	1.0
  (4, 61)	1.0
  (5, 75)	1.0
Dimension: (6, 165)

Sentence: ['sneaker', 'uncomfortable', 'look', 'cheap']
  (0, 136)	1.0
  (1, 150)	1.0
  (2, 85)	1.0
  (3, 20)	1.0
Dimension: (4, 165)

Sentence: ['customer', 'service', 'help', 'laptop', 'broke']
  (0, 30)	1.0
  (1, 127)	1.0
  (2, 64)	1.0
  (3, 77)	1.0
  (4, 15)	1.0
Dimension: (5, 165)

Sentence: ['effective', 'jacket', 'least', 'affordable']
  (0, 43)	1.0
  (1, 73)	1.0
  (2, 80)	1.0
  (3, 1)	1.0
Dimension: (4, 165)

Sentence: ['pair', 'jean', 'wellbuilt', 'easy', 'use']
  (0, 108)	1.0
  (1, 74)	1.0
  (2, 160)	1.0
  (3, 42)	1.0
  (4, 153)	1.0
Dimension: (5, 165)

Sentence: ['absolutely', 'love', 'sneaker', 'exceeded', 'expectation']
  (0, 0)	1.0
  (1, 87)	1.0
  (2, 136)	1.0
  (3, 48)	1.0
  (4, 50)	1.0
Dimension: (5, 165)

Sentence: ['sneaker', 'stylish', 'comfortable', 'use']
  (0, 136)	1.0

## BOW

In [33]:
#Count vectorisation for reviews_cleaned
from sklearn.feature_extraction.text import CountVectorizer
cnt_vect = CountVectorizer()
cnt_vect.fit(reviews_cleaned)
encoded_reviews_cnt_vect = cnt_vect.fit_transform(reviews_cleaned)
print("dimension:", cnt_vect.get_feature_names_out().shape[0])
print("Vocabulary:", cnt_vect.get_feature_names_out())
print(encoded_reviews_cnt_vect.toarray())

#Merging the BOW to the main data for further machine learning model building

encoded_reviews_df_bow = pd.DataFrame(encoded_reviews_cnt_vect.toarray(), columns=cnt_vect.get_feature_names_out())
final_df_cnt_bow= pd.concat([data, encoded_reviews_df_bow], axis=1)    
final_df_cnt_bow.head()

dimension: 165
Vocabulary: ['absolutely' 'affordable' 'air' 'already' 'although' 'amazing' 'anyone'
 'arrived' 'battery' 'best' 'biography' 'bit' 'blender' 'bluetooth' 'book'
 'broke' 'bulky' 'buying' 'came' 'changer' 'cheap' 'clean' 'clearer'
 'coffee' 'color' 'comfortable' 'compact' 'compliment' 'cookbook' 'could'
 'customer' 'damaged' 'day' 'description' 'design' 'didnt' 'disappointed'
 'disappointing' 'disappoints' 'doesnt' 'dress' 'easier' 'easy'
 'effective' 'efficient' 'especially' 'ever' 'every' 'exceeded'
 'excellent' 'expectation' 'fantastic' 'fast' 'feature' 'feel' 'first'
 'fit' 'flawlessly' 'friend' 'fryer' 'game' 'great' 'hard' 'headphone'
 'help' 'high' 'highly' 'hope' 'impressive' 'inefficient' 'instruction'
 'intuitive' 'ive' 'jacket' 'jean' 'kitchen' 'knife' 'laptop' 'lasted'
 'late' 'least' 'let' 'life' 'lightweight' 'longer' 'look' 'looking'
 'love' 'made' 'maintain' 'maker' 'many' 'match' 'meet' 'missing' 'money'
 'much' 'never' 'nice' 'noisy' 'novel' 'offer' 'one' 'overall' 'overheats'
 'overpriced' 'owned' 'packaging' 'pair' 'part' 'penny' 'perfectly'
 'performance' 'performs' 'poor' 'poorly' 'price' 'pricey' 'quality'
 'quickly' 'received' 'recommend' 'recommended' 'regret' 'reliable'
 'return' 'selfhelp' 'service' 'set' 'setup' 'shipping' 'skeptical'
 'sleek' 'slow' 'smartphone' 'smell' 'sneaker' 'speaker' 'stopped' 'store'
 'stylish' 'tablet' 'terrible' 'textbook' 'though' 'time' 'toaster'
 'tricky' 'tshirt' 'turned' 'uncomfortable' 'unresponsive' 'unsafe' 'use'
 'used' 'userfriendly' 'value' 'week' 'weird' 'well' 'wellbuilt' 'wish'
 'work' 'working' 'worth']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]

,review,label,cleaned_review,absolutely,affordable,air,already,although,amazing,anyone,...,userfriendly,value,week,weird,well,wellbuilt,wish,work,working,worth
0,Customer service was no help when the t-shirt ...,0,customer service help tshirt broke,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,The pair of jeans is slow and unresponsive.,0,pair jean slow unresponsive,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,The air fryer is too noisy and inefficient.,0,air fryer noisy inefficient,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,"The air fryer is disappointing, although it do...",0,air fryer disappointing although look nice,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,The smartphone doesn’t match the description.,0,smartphone doesnt match description,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## TF-IDF

In [34]:
#TF IDF with reviews_cleaned
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer()
tfidf_vect.fit(reviews_cleaned)
encoded_reviews_tfidf_vect = tfidf_vect.fit_transform(reviews_cleaned)
print("dimension:", tfidf_vect.get_feature_names_out().shape[0])
print("Vocabulary:", tfidf_vect.get_feature_names_out())
print(encoded_reviews_tfidf_vect.toarray())

#Merging the BOW to the main data for further machine learning model building

encoded_reviews_df_tfidf = pd.DataFrame(encoded_reviews_tfidf_vect.toarray(), columns=tfidf_vect.get_feature_names_out())
final_df_cnt_tfidf= pd.concat([data,encoded_reviews_df_tfidf], axis=1)    
final_df_cnt_tfidf.head()

dimension: 165
Vocabulary: ['absolutely' 'affordable' 'air' 'already' 'although' 'amazing' 'anyone'
 'arrived' 'battery' 'best' 'biography' 'bit' 'blender' 'bluetooth' 'book'
 'broke' 'bulky' 'buying' 'came' 'changer' 'cheap' 'clean' 'clearer'
 'coffee' 'color' 'comfortable' 'compact' 'compliment' 'cookbook' 'could'
 'customer' 'damaged' 'day' 'description' 'design' 'didnt' 'disappointed'
 'disappointing' 'disappoints' 'doesnt' 'dress' 'easier' 'easy'
 'effective' 'efficient' 'especially' 'ever' 'every' 'exceeded'
 'excellent' 'expectation' 'fantastic' 'fast' 'feature' 'feel' 'first'
 'fit' 'flawlessly' 'friend' 'fryer' 'game' 'great' 'hard' 'headphone'
 'help' 'high' 'highly' 'hope' 'impressive' 'inefficient' 'instruction'
 'intuitive' 'ive' 'jacket' 'jean' 'kitchen' 'knife' 'laptop' 'lasted'
 'late' 'least' 'let' 'life' 'lightweight' 'longer' 'look' 'looking'
 'love' 'made' 'maintain' 'maker' 'many' 'match' 'meet' 'missing' 'money'
 'much' 'never' 'nice' 'noisy' 'novel' 'offer' 'one' 'overall' 'overheats'
 'overpriced' 'owned' 'packaging' 'pair' 'part' 'penny' 'perfectly'
 'performance' 'performs' 'poor' 'poorly' 'price' 'pricey' 'quality'
 'quickly' 'received' 'recommend' 'recommended' 'regret' 'reliable'
 'return' 'selfhelp' 'service' 'set' 'setup' 'shipping' 'skeptical'
 'sleek' 'slow' 'smartphone' 'smell' 'sneaker' 'speaker' 'stopped' 'store'
 'stylish' 'tablet' 'terrible' 'textbook' 'though' 'time' 'toaster'
 'tricky' 'tshirt' 'turned' 'uncomfortable' 'unresponsive' 'unsafe' 'use'
 'used' 'userfriendly' 'value' 'week' 'weird' 'well' 'wellbuilt' 'wish'
 'work' 'working' 'worth']
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.49231788 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.34734403 0.         0.        ]]

,review,label,cleaned_review,absolutely,affordable,air,already,although,amazing,anyone,...,userfriendly,value,week,weird,well,wellbuilt,wish,work,working,worth
0,Customer service was no help when the t-shirt ...,0,customer service help tshirt broke,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,The pair of jeans is slow and unresponsive.,0,pair jean slow unresponsive,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,The air fryer is too noisy and inefficient.,0,air fryer noisy inefficient,0.0,0.0,0.492318,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,"The air fryer is disappointing, although it do...",0,air fryer disappointing although look nice,0.0,0.0,0.388458,0.0,0.392307,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,The smartphone doesn’t match the description.,0,smartphone doesnt match description,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## ML

In [35]:
#lets fit a logistic regression model on the count vectorised data
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

log_reg = LogisticRegression()

#test train split for the data
X_train, X_test, y_train, y_test = train_test_split(data['cleaned_review'], data['label'], test_size=0.2, random_state=42)

threshold=0.6

## ML with BOW

In [36]:
#Vectorising with BOW

from sklearn.feature_extraction.text import CountVectorizer
bow= CountVectorizer()
X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

#ML Training
log_reg.fit(X_train_bow, y_train)

probs=log_reg.predict_proba(X_test_bow)[:,1]
threshold=threshold
y_pred = (probs >= threshold).astype(int)

print(classification_report(y_test, y_pred))
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

#Predict new review

new_review = "This product is amazing! I love it."
new_review_cleaned = preprocess_text(new_review)
new_review_cleaned = remove_punctuation(new_review_cleaned)
new_review_cleaned = remove_hyphens(new_review_cleaned)
new_review_bow = bow.transform([new_review_cleaned])


Threshold_pred=threshold
predicted_prob = log_reg.predict_proba(new_review_bow)
predicted_label= (predicted_prob[:, 1] >= Threshold_pred).astype(int)

print(f"Review: '{new_review}'")
print(f"Predicted Label: {predicted_label[0]}")
predicted_prob = log_reg.predict_proba(new_review_bow)
print(f"Predicted Probabilities: {predicted_prob[0]}")
print(f"classes: {log_reg.classes_}")

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        47
           1       1.00      1.00      1.00        53

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

Confusion Matrix:
 [[47  0]
 [ 0 53]]
Review: 'This product is amazing! I love it.'
Predicted Label: 1
Predicted Probabilities: [0.21349644 0.78650356]
classes: [0 1]

## TF IDF

In [37]:

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()


X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

#ML Training
log_reg.fit(X_train_tfidf, y_train)

probs=log_reg.predict_proba(X_test_tfidf)[:,1]
threshold=threshold
y_pred = (probs >= threshold).astype(int)

print(classification_report(y_test, y_pred))
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

#Predict new review

new_review = "This product is amazing! I love it."
new_review_cleaned = preprocess_text(new_review)
new_review_cleaned = remove_punctuation(new_review_cleaned)
new_review_cleaned = remove_hyphens(new_review_cleaned)
new_review_tfidf = tfidf.transform([new_review_cleaned])


Threshold_pred=threshold
predicted_prob = log_reg.predict_proba(new_review_tfidf)
predicted_label= (predicted_prob[:, 1] >= Threshold_pred).astype(int)

print(f"Review: '{new_review}'")
print(f"Predicted Label: {predicted_label[0]}")
predicted_prob = log_reg.predict_proba(new_review_tfidf)
print(f"Predicted Probabilities: {predicted_prob[0]}")
print(f"classes: {log_reg.classes_}")

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        47
           1       1.00      1.00      1.00        53

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

Confusion Matrix:
 [[47  0]
 [ 0 53]]
Review: 'This product is amazing! I love it.'
Predicted Label: 1
Predicted Probabilities: [0.2324453 0.7675547]
classes: [0 1]

## Comparison with completely new data

In [38]:
data_new = pd.read_csv(r"D:\GEN_AI_BOOTCAMP\Live_Classes1\Assignments\Data\new_amazon_reviews.csv")
new_review_cleaned = data_new["review"].apply(preprocess_text)
new_review_cleaned = new_review_cleaned.apply(remove_punctuation)
new_review_cleaned = new_review_cleaned.apply(remove_hyphens)
Threshold_pred=0.6

#Vectorising the new review
new_review_bow= bow.transform(new_review_cleaned)   #USING TRANSFORM ONLY AS VECTORISOR IS ALREADY FITTED ON THE TRAINING DATA
new_review_tfidf = tfidf.transform(new_review_cleaned)


pred_prob_bow = log_reg.predict_proba(new_review_bow)
pred_bow= (pred_prob_bow[:, 1] >= Threshold_pred).astype(int)
pred_prob_tfidf = log_reg.predict_proba(new_review_tfidf)
pred_tfidf= (pred_prob_tfidf[:, 1] >= Threshold_pred).astype(int)

confusion_matrix_bow = confusion_matrix(data_new['label'], pred_bow)
confusion_matrix_tfidf = confusion_matrix(data_new['label'], pred_tfidf)

accuracy_bow = (confusion_matrix_bow[0, 0] + confusion_matrix_bow[1, 1]) / confusion_matrix_bow.sum()
accuracy_tfidf = (confusion_matrix_tfidf[0, 0] + confusion_matrix_tfidf[1, 1]) / confusion_matrix_tfidf.sum()

precision_bow = confusion_matrix_bow[1, 1] / (confusion_matrix_bow[0, 1] + confusion_matrix_bow[1, 1])
precision_tfidf = confusion_matrix_tfidf[1, 1] / (confusion_matrix_tfidf[0, 1] + confusion_matrix_tfidf[1, 1])

recall_bow = confusion_matrix_bow[1, 1] / (confusion_matrix_bow[1, 0] + confusion_matrix_bow[1, 1])
recall_tfidf = confusion_matrix_tfidf[1, 1] / (confusion_matrix_tfidf[1, 0] + confusion_matrix_tfidf[1, 1])

f1_score_bow = 2 * (precision_bow * recall_bow) / (precision_bow + recall_bow)
f1_score_tfidf = 2 * (precision_tfidf * recall_tfidf) / (precision_tfidf + recall_tfidf)

print("Confusion Matrix for BOW:\n", confusion_matrix_bow)
print("Confusion Matrix for TF-IDF:\n", confusion_matrix_tfidf)

print(f"Accuracy with BOW: {accuracy_bow:.2f}")
print(f"Accuracy with TF-IDF: {accuracy_tfidf:.2f}")
print(f"Precision with BOW: {precision_bow:.2f}")
print(f"Precision with TF-IDF: {precision_tfidf:.2f}")
print(f"Recall with BOW: {recall_bow:.2f}")
print(f"Recall with TF-IDF: {recall_tfidf:.2f}")
print(f"F1 Score with BOW: {f1_score_bow:.2f}")
print(f"F1 Score with TF-IDF: {f1_score_tfidf:.2f}")

#Merge the predictions with the main data
data_new["predicted_label_bow"] = pred_bow
data_new["predicted_label_tfidf"] = pred_tfidf
data_new["predicted_prob_bow"] = pred_prob_bow[:, 1]
data_new["predicted_prob_tfidf"] = pred_prob_tfidf[:, 1]
data_new.head()

Confusion Matrix for BOW:
 [[248   2]
 [  0 250]]
Confusion Matrix for TF-IDF:
 [[250   0]
 [  0 250]]
Accuracy with BOW: 1.00
Accuracy with TF-IDF: 1.00
Precision with BOW: 0.99
Precision with TF-IDF: 1.00
Recall with BOW: 1.00
Recall with TF-IDF: 1.00
F1 Score with BOW: 1.00
F1 Score with TF-IDF: 1.00

,review,label,predicted_label_bow,predicted_label_tfidf,predicted_prob_bow,predicted_prob_tfidf
0,"Absolutely love this knife set, it exceeded my...",1,1,1,0.970475,0.797315
1,Highly recommend this jacket to anyone looking...,1,1,1,0.875049,0.685117
2,The smartphone has excellent features and is v...,1,1,1,0.894854,0.738682
3,The coffee maker has a weird smell and feels u...,0,0,0,0.103340,0.252357
4,This is the best textbook I've ever owned!,1,1,1,0.972418,0.812863

In [39]:
# EXPORT TO EXCEL
data_new.to_excel(r"D:\GEN_AI_BOOTCAMP\Live_Classes1\Assignments\Data\new_amazon_reviews_with_predictions.xlsx", index=False)